version: "3.9"
services:
  springboot-app:
#    container_name: spring-app
    image: springboot-app
    restart: always
    build: .
    ports:
      - "8081:8081"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_PORT: 3306


  mysqldb:
    container_name: mysqldb-compose
    image: mysql
    volumes:
      -  C:\Users\salma\OneDrive\Desktop\db:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: test1
      MYSQL_ROOT_PASSWORD: 1234
#      DATABASE_HOST: mysql-db
#      DATABASE_PORT: 3306
#      MYSQL_USER: root
#      MYSQL_PASSWORD: 1234

